"use client";
import "../styles/globals.css";
import { Inter } from "next/font/google";

import AuthProvider from "./components/Next-Auth";
const inter = Inter({ subsets: ["latin"] });

// import KakaoLoginButton from "./components/kakaoLoginButton";
import Navbar from "./components/Navbar/Navbar";
import Script from "next/script";
import { usePathname, useRouter } from "next/navigation";

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

declare global {
    interface Window {
        kakao: any;
    }
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const router = useRouter();
    const pathname = usePathname().slice(1);
    console.log(pathname);

    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthProvider>
                    {children}
                    {pathname !== "login" ? <Navbar /> : null}
                </AuthProvider>
            </body>
        </html>
    );
}
